### ISSUE TITLE
Create reference table

### ISSUE THREAD

**Issue by rosemerryberry** [jlibman/info370-finalproject#19]
This table will live on the exploration page, below the plots, that show what question translates into which covariate label. Only include questions that are shown in the covariate options list (aka no state or country or outcomes of interest or work_interference)

**Comment by CalvinKorver** [comment]
So we just need a table describing what each of the covariates means? I can do that.

We should also have tables referencing what each outcome of interest means what...

**Comment by rosemerryberry** [comment]
I talk about what the outcomes of interest represent, but that is a great idea! If you can do that as well that would be ideal. You can also find all of the original questions and what they mean either in our 370 final paper doc or here https://www.kaggle.com/osmi/mental-health-in-tech-survey

**Comment by CalvinKorver** [comment]
Created a function in `CovariateExplanations.R` that returns a dataframe with columns covariate and definition that you can utilize in the Shiny App. Closing for now.
