### ISSUE TITLE
Pick 3 ways to improve mental health acceptance in the workplace

### ISSUE THREAD

**Issue by rosemerryberry** [jlibman/info370-finalproject#24]
Based on the results of the three models, pick 3 concrete strategies a company or supervisor could use to improve the social acceptance of mental health in their office.

Ideally, there would be one strategy for each outcome of interest, but these can apply to all outcomes simultaneously.

Write up your recommendations in the "recommendations" tab of the site.

**Comment by CalvinKorver** [comment]
We need results to do this, right? And there is no recommendations tab yet, but I can start drafting something.

**Comment by rosemerryberry** [comment]
We do need results to do this - so you'll have to wait to start. I'm going to push up my changes and scaffolding in a second.
